apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: default
  labels:
    k8s-app: mongo
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: mongo
  labels:
    k8s-app: mongo
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
